version: "3.8"
services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports: [ "9000:9000", "9001:9001" ]
    volumes: [ "./.data/minio:/data" ]

  suricata:
    image: jasonish/suricata:latest
    network_mode: host
    cap_add: [ "NET_ADMIN", "NET_RAW" ]
    volumes:
      - ./suricata:/etc/suricata
      - ./suricata/log:/var/log/suricata
      - ./suricata/filestore:/var/lib/suricata/filestore

  surisink:
    build: .
    environment:
      CONFIG_PATH: /app/config.yaml
    volumes:
      - ./configs/config.yaml:/app/config.yaml
      - ./suricata/log:/var/log/suricata
      - ./suricata/filestore:/var/lib/suricata/filestore
    depends_on: [ minio ]
