suricata:
  eve_json_path: "/var/log/suricata/eve.json"
  filestore_dir: "/var/lib/suricata/filestore"
  path_strategy: "file_id"       # "absolute" | "file_id"
  file_naming_pattern: "file.%d" # e.g., file.12345
  use_date_subdirs: false
  date_layout: "2006/01/02"

uploader:
  workers: 4
  prefix: "suricata"
  max_retries: 5
  backoff_ms: 500

s3:
  endpoint: "http://localhost:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket: "evidence"
  use_ssl: false

dedupe:
  enabled: true
  sqlite_path: "./data/surisink.db"
  retention_days: 0

logging:
  level: "info"     # debug|info|warn|error
  format: "json"    # json|console
