suricata:
  eve_json_path: "/var/log/suricata/eve.json"
  filestore_dir: "/var/lib/suricata/filestore"
  # Strategy to resolve file path from eve.json:
  # - "absolute": use fileinfo.filename if it's an absolute path and exists
  # - "file_id": build from filestore_dir + file_naming_pattern (default "file.%d")
  path_strategy: "file_id"
  file_naming_pattern: "file.%d"
  use_date_subdirs: false       # set true if your filestore uses date subdirs
  date_layout: "2006/01/02"     # only used when use_date_subdirs=true

uploader:
  workers: 4
  prefix: "suricata"
  max_retries: 5
  backoff_ms: 500

s3:
  endpoint: "http://localhost:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket: "evidence"
  use_ssl: false


logging:
  level: "info"     # debug|info|warn|error
  format: "json"    # json|console


dedupe:
  enabled: true
  sqlite_path: "./data/surisink.db"
